# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mindctl < Formula
  desc "An LLM router that uses built-in logic and system 1 decision models to intelligently route requests to the appropriate LLM based on the input prompt"
  homepage "https://github.com/storm-software/mindctl"
  version "0.1.39"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/storm-software/mindctl/releases/download/v0.1.39/mindctl_0.1.39_darwin-amd64.tar.gz"
      sha256 "4703473bf7cc0d51336f47b68965138f1ee84e8874165b1de79e223cb13ecae1"

      define_method(:install) do
        bin.install "mindctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/storm-software/mindctl/releases/download/v0.1.39/mindctl_0.1.39_darwin-arm64.tar.gz"
      sha256 "ee27ce9f7ca4ffc65d96840223dec96faeb4bff4f0668a1baddf7f5049ee4bdf"

      define_method(:install) do
        bin.install "mindctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/storm-software/mindctl/releases/download/v0.1.39/mindctl_0.1.39_linux-amd64.tar.gz"
      sha256 "c63de1801ad5084f27f2fa242b3500b760b4ca29cce740ab400cf1cabcf784ce"
      define_method(:install) do
        bin.install "mindctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/storm-software/mindctl/releases/download/v0.1.39/mindctl_0.1.39_linux-arm64.tar.gz"
      sha256 "3c72764c1d067abcc3ec9c118eecd18bfd94c81e185c6e38c3002c92e539840c"
      define_method(:install) do
        bin.install "mindctl"
      end
    end
  end

  test do
    system "#{bin}/mindctl", "--help"
  end
end
