# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mindctl < Formula
  desc "An LLM router that uses built-in logic and system 1 decision models to intelligently route requests to the appropriate LLM based on the input prompt"
  homepage "https://github.com/storm-software/mindctl"
  version "0.1.21"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/storm-software/mindctl/releases/download/v0.1.21/mindctl_0.1.21_darwin-amd64.tar.gz"
      sha256 "cee0d085d504907b2925c26dec453b90d7da4017356ba5a81de67074ee34516a"

      define_method(:install) do
        bin.install "mindctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/storm-software/mindctl/releases/download/v0.1.21/mindctl_0.1.21_darwin-arm64.tar.gz"
      sha256 "e412b18e4a6a00348f73f3c49e4c659b1059f84668cb0e466b6da8e3dbd8f86e"

      define_method(:install) do
        bin.install "mindctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/storm-software/mindctl/releases/download/v0.1.21/mindctl_0.1.21_linux-amd64.tar.gz"
      sha256 "b5d8051d82abf413633b746147d98dd4eb6998853fba537d80e3d1de9bf4125e"
      define_method(:install) do
        bin.install "mindctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/storm-software/mindctl/releases/download/v0.1.21/mindctl_0.1.21_linux-arm64.tar.gz"
      sha256 "806ca3427c5aa19af92d9b1740b13fbb48788a8cef286723b901fc20c5d4be47"
      define_method(:install) do
        bin.install "mindctl"
      end
    end
  end

  test do
    system "#{bin}/mindctl", "--help"
  end
end
