# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mindctl < Formula
  desc "An LLM router that uses built-in logic and system 1 decision models to intelligently route requests to the appropriate LLM based on the input prompt"
  homepage "https://github.com/storm-software/mindctl"
  version "0.1.20"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/storm-software/mindctl/releases/download/v0.1.20/mindctl_0.1.20_darwin-amd64.tar.gz"
      sha256 "47e9aa512d4e15adfdc8c35ce20873ea4c5c844f587f4465a5bcade5e80784d4"

      define_method(:install) do
        bin.install "mindctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/storm-software/mindctl/releases/download/v0.1.20/mindctl_0.1.20_darwin-arm64.tar.gz"
      sha256 "689d95f3369c88b3826679852b515cd978313889dc18d8d5fa8071354cf31513"

      define_method(:install) do
        bin.install "mindctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/storm-software/mindctl/releases/download/v0.1.20/mindctl_0.1.20_linux-amd64.tar.gz"
      sha256 "e3ac9ab9f2118e5a46ad54134d7196f31b09d491602d6824113fe005507e6976"
      define_method(:install) do
        bin.install "mindctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/storm-software/mindctl/releases/download/v0.1.20/mindctl_0.1.20_linux-arm64.tar.gz"
      sha256 "da32cea265d8d17bf73ed341dee8d1f6d8bb992cc8d1e2f1fc7f6ea12d1258c4"
      define_method(:install) do
        bin.install "mindctl"
      end
    end
  end

  test do
    system "#{bin}/mindctl", "--help"
  end
end
