version: 2
project_name: mindctl

builds:
  - id: mindctl
    main: ./cmd/mindctl
    binary: mindctl
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commit={{ .Commit }} -X main.date={{ .Date }}

archives:
  - id: mindctl
    ids: [mindctl]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}-{{ .Arch }}"
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE

brews:
  - repository:
      owner: storm-software
      name: mindctl
    directory: HomebrewFormula
    homepage: "https://github.com/storm-software/mindctl"
    description: "An LLM router that uses built-in logic and system 1 decision models to intelligently route requests to the appropriate LLM based on the input prompt"
    license: "Apache-2.0"
    test: |
      system "#{bin}/mindctl", "--help"

checksum:
  name_template: checksums.txt

release:
  draft: true
